Repository antrc2/Project-1, pull requests merged in 2024-11, with the labels that each got.

#11 fix session remove
  commons/functions.php
Labels: help wanted

#20 add UD discount
  commons/functions.php
  controllers/discountController.php
  index.php
  models/discountModel.php
  views/admin/discount/readDiscount.php
  views/admin/discount/updateDiscount.php
Labels: feature

#22 Hieudp
  assets/img/67380791284018.27122881.jpg
  assets/img/673807912948f4.20702273.jpg
  assets/img/6738be170fea27.41881810.jpg
  assets/img/6738be17105854.71577406.jpg
  assets/img/6738be17108ec7.03666205.jpg
  assets/img/6738beaed28ab7.15871730.jpg
  assets/img/6738beaed2d8d7.56233071.jpg
  assets/img/6738beaed31031.14529797.jpg
  assets/img/6738bf9a796832.35294234.jpg
  assets/img/6738c050d52016.55151154.jpg
  assets/img/6738c0551326d0.24395719.jpg
  assets/img/6738c070641828.75492386.jpg
  assets/img/6738c07506ac93.76251137.jpg
  assets/img/6738c084f21bb1.51521417.jpg
  assets/img/6738c084f2b1f4.80124829.jpg
  assets/img/6738c084f336e1.31971519.jpg
  assets/img/6738c16c2c5ef5.62063864.jpg
  assets/img/6738c16c2cd907.34144859.jpg
  assets/img/6738c16c2d47d3.94294536.jpg
  assets/img/673a0993abb786.88374055.jpg
  assets/img/673a0993acdd51.85427857.jpg
  assets/img/673a0993ad5f08.64630090.jpg
  assets/img/673a1c324b9bd1.79012708.jpg
  assets/img/673a1c324c6142.85797711.jpg
  assets/img/673a1c324cd387.22460050.jpg
  assets/img/tải xuống (4).jpg
  assets/img/tải xuống (6).jpg
  commons/functions.php
  controllers/productController.php
  index.php
  models/productModel.php
  views/admin/product/chitietsanpham.php
  views/admin/product/createProduct.php
  views/admin/product/suasanpham.php
Labels: feature

#35 CRUD product image detail
  assets/img/6740afca4156c.jpg
  assets/img/6740afd558734.jpg
  assets/img/6740b0b5a441f.jpg
  commons/functions.php
  controllers/productController.php
  models/accountModel.php
  views/admin/product/suasanpham.php
Labels: bug

#36 Add template
  index.php
Labels: feature

#38 return model to template
  assets/img/674225e52fbae.jpg
  assets/web/css/admin.css
  assets/web/css/style.css
  controllers/cartController.php
  controllers/homeController.php
  index.php
  models/cartModel.php
  models/productModel.php
  views/user/components/head.php
  views/user/components/nav.php
  views/user/home/home.php
Labels: feature

#39 add detail product for user anđ fix database
  commons/functions.php
  controllers/homeController.php
  index.php
  models/discountModel.php
  models/productModel.php
  project1.sql
  views/user/home/chitietsanpham.php
  views/user/home/home.php
Labels: feature

#53 add CRUD cart
  commons/functions.php
  controllers/cartController.php
  controllers/homeController.php
  index.php
  models/cartModel.php
  project1.sql
  views/user/home/giohang.php
  views/user/home/thanhtoan.php
Labels: feature
